package com.foodquart.microservicefoodcourt.application.handler;

import com.foodquart.microservicefoodcourt.application.dto.request.CreateRestaurantEmployeeRequestDto;
import com.foodquart.microservicefoodcourt.application.dto.response.CreateRestaurantEmployeeResponseDto;

public interface IRestaurantEmployeeHandler {
    CreateRestaurantEmployeeResponseDto addEmployeeToRestaurant(Long restaurantId, CreateRestaurantEmployeeRequestDto createRestaurantEmployeeRequestDto);
}
